#!/usr/bin/bash

if [ "$#" -ne "2" ] ; then
  echo "This script requires two arguments:"
  echo "  NAMD input file "
  echo "  NAMD output file "
  exit -1
fi

if [ "$SLURM_NNODES" -ne "$SLURM_NTASKS" ] ; then
  echo "The number of task per node is NOT 1! Please use same number in -n x -N x in your job submission."
  exit -1
fi

module load cuda/12.6
module load nvmath/12.6.0
module load openmpi/5.0.5
module load ucx/1.18.0
module load namd-gpu/3.0.2

pemap="1-71"
commap="0"
ppn=71

srun --mpi=pmi2 $TACC_NAMD_GPU_BIN/namd3 +ppn $ppn +pemap $pemap +commap $commap +devices 0 $1 &> $2