#!/bin/bash
#SBATCH -J test   # Job Name
#SBATCH -A A-ccsc
#SBATCH -o test.out
#SBATCH -e test.err
#SBATCH -N 1      # Total number of nodes
#SBATCH -n 1      # Total number of mpi tasks
#SBATCH -p gh     # Queue name
#SBATCH -t 00:03:00 # Run time (hh:mm:ss) - 24 hours

module load cuda/12.6
module load nvmath/12.6.0
module load openmpi/5.0.5
module load ucx/1.18.0
module load namd-gpu/3.0.2
      
run_namd_gpu apoa1.namd test.out